export const routes = {
  home: {
    dashboard: '/dashboard',
  },
  plants: {
    dashboard: '/c/plants/dashboard',
    projects: '/c/plants/projects',
    projectsMine: '/c/plants/projects/mine',
    orders: '/c/plants/orders',
    ordersCreate: '/c/plants/orders/create',
    reports: '/c/plants/analytics/reports',
  },
  carbon: {
    dashboard: '/c/carbon/dashboard',
    emissions: '/c/carbon/emissions',
    emissionsCreate: '/c/carbon/emissions/create',
    exclusions: '/c/carbon/exclusions',
    siteProjects: '/c/carbon/sites/projects',
    sitePlans: '/c/carbon/sites/plans',
    suppliers: '/c/carbon/suppliers',
    clients: '/c/carbon/clients',
    factors: '/c/carbon/factors',
    factorsCustom: '/c/carbon/factors/custom',
    factorsCustomCreate: '/c/carbon/factors/custom/create',
    reports: '/c/carbon/analytics/reports',
  },
  esg: {
    dashboard: '/c/esg/dashboard',
    envMetrics: '/c/esg/environmental/metrics',
    envTargets: '/c/esg/environmental/targets',
    socialMetrics: '/c/esg/social/metrics',
    socialInitiatives: '/c/esg/social/initiatives',
    govPolicies: '/c/esg/governance/policies',
    govBoard: '/c/esg/governance/board',
    gri: '/c/esg/frameworks/gri',
    sasb: '/c/esg/frameworks/sasb',
    tcfd: '/c/esg/frameworks/tcfd',
    cdp: '/c/esg/frameworks/cdp',
    regulations: '/c/esg/compliance/regulations',
    audits: '/c/esg/compliance/audits',
    certifications: '/c/esg/compliance/certifications',
    goals: '/c/esg/targets/goals',
    kpi: '/c/esg/targets/kpi',
    progress: '/c/esg/targets/progress',
  },
  reports: {
    dashboard: '/c/reports/dashboard',
    builder: '/c/reports/builder',
    published: '/c/reports/published',
    scheduled: '/c/reports/scheduled',
    dataSources: '/c/reports/data/sources',
    dataForms: '/c/reports/data/forms',
    dataFormsCreate: '/c/reports/data/forms/create',
    importExport: '/c/reports/data/import-export',
    templates: '/c/reports/templates',
    sections: '/c/reports/templates/sections',
    trends: '/c/reports/analytics/trends',
    benchmarks: '/c/reports/analytics/benchmarks',
  },
  geo: {
    dashboard: '/c/geo/dashboard',
    map: '/c/geo/map',
    mapSatellite: '/c/geo/map/satellite',
    sites: '/c/geo/sites',
    sitesCreate: '/c/geo/sites/create',
    zones: '/c/geo/sites/zones',
    sensors: '/c/geo/sensors',
    sensorData: '/c/geo/sensors/data',
    sensorAlerts: '/c/geo/sensors/alerts',
    layerAir: '/c/geo/layers/air',
    layerWater: '/c/geo/layers/water',
    layerSoil: '/c/geo/layers/soil',
    layerBiodiversity: '/c/geo/layers/biodiversity',
    spatialReports: '/c/geo/analytics/reports',
    changeDetection: '/c/geo/analytics/changes',
  },
};
